language: python
python:

- "3.9"

env:
  - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start
  
install:
  - sudo apt-get install python3-tk
  - sudo apt-get install rake

script: python Steam-Auto-Shutdown-Linux.py
