language: python
python:

- "3.9"
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
    
before_install:
  - export DISPLAY=:99.0 
sudo: required  
install:
  - sudo apt-get install python3-tk
  - sudo apt-get install rake

script: python Steam-Auto-Shutdown-Linux.py
